#!/usr/bin/env node
// Renders web/public/css/tokens.css from docs/design/tokens.json, the mirror of the Figma `Design` variables and
// styles (ADR-031 § 8, ADR-037 § 4). Names follow each variable's WEB code syntax (`var(--color-bg-page)`).
// Light values sit on :root, Dark values on :root[data-theme="dark"]. Text styles become .t-<name> classes and
// --text-<name>-{weight,size,line,tracking} properties (for responsive swaps). Never edit the output by hand.
//
// Usage: node tools/build-tokens.mjs           writes public/css/tokens.css
//        node tools/build-tokens.mjs --check   exits 1 when the file is stale (no write)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.resolve(web, "..", "docs", "design", "tokens.json");
const TARGET = path.join(web, "public", "css", "tokens.css");

const WEIGHTS = { Regular: 400, Medium: 500, SemiBold: 600, Bold: 700, ExtraBold: 800 };

const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const cssName = (v) => v.codeSyntax?.WEB?.match(/var\((--[a-z0-9-]+)\)/)?.[1] ?? "--" + slug(v.name);

function hexColor(value) {
  const m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(value);
  if (!m) throw new Error(`bad color '${value}'`);
  return m[2] && m[2].toLowerCase() !== "ff" ? `#${m[1]}${m[2]}`.toLowerCase() : `#${m[1]}`.toLowerCase();
}

function floatValue(v, value) {
  if (v.name.startsWith("motion/")) return `${value}ms`;
  return `${value}px`;
}

export function render(tokens) {
  const byName = new Map();
  const light = [];
  const dark = [];
  const fixed = [];
  for (const c of tokens.collections) {
    for (const v of c.variables) {
      const name = cssName(v);
      byName.set(v.name, name);
      if (v.type === "COLOR") {
        light.push(`  ${name}: ${hexColor(v.values.Light)};`);
        dark.push(`  ${name}: ${hexColor(v.values.Dark)};`);
      } else if (v.type === "FLOAT") {
        fixed.push(`  ${name}: ${floatValue(v, v.values.Value)};`);
      } else if (v.type === "STRING") {
        fixed.push(`  ${name}: ${v.values.Value};`);
      }
    }
  }
  const ref = (stop) => (stop.variable ? `var(${byName.get(stop.variable) ?? fail(stop.variable)})` : hexColor(stop.color));
  const paints = [];
  for (const s of tokens.paintStyles) {
    // Figma lists paints bottom first; CSS backgrounds list the top layer first.
    const layers = [...s.paints].reverse().map((p) => {
      if (p.type === "SOLID") return `linear-gradient(${ref(p)}, ${ref(p)})`;
      if (p.type === "GRADIENT_LINEAR" && p.direction === "topToBottom")
        return `linear-gradient(to bottom, ${p.stops.map((st) => `${ref(st)} ${+(st.position * 100).toFixed(2)}%`).join(", ")})`;
      throw new Error(`unsupported paint in ${s.name}`);
    });
    paints.push(`  --paint-${slug(s.name)}: ${layers.join(", ")};`);
  }
  const effects = [];
  for (const s of tokens.effectStyles) {
    const shadows = [];
    for (const e of s.effects) {
      if (e.type === "BACKGROUND_BLUR") effects.push(`  --effect-${slug(s.name)}-blur: blur(${e.variable ? `var(${byName.get(e.variable)})` : e.radius + "px"});`);
      else if (e.type === "DROP_SHADOW") shadows.push(`${e.offsetX}px ${e.offsetY}px ${e.radius}px ${e.spread}px ${e.variable ? `var(${byName.get(e.variable)})` : hexColor(e.color)}`);
      else throw new Error(`unsupported effect in ${s.name}`);
    }
    if (shadows.length) effects.push(`  --effect-${slug(s.name)}-shadow: ${shadows.join(", ")};`);
  }
  const text = [];
  const textVars = [];
  const families = new Set(tokens.textStyles.map((s) => s.family));
  if (families.size !== 1) throw new Error("expected one font family in the text styles");
  const fontVar = `  --font-family-base: "${[...families][0]}", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;`;
  for (const s of tokens.textStyles) {
    if (s.family !== "Nunito Sans") throw new Error(`text style ${s.name} is not Nunito Sans`);
    const weight = WEIGHTS[s.style] ?? fail(`weight ${s.style}`);
    const rules = [
      `font-weight: ${weight};`,
      `font-size: ${s.size}px;`,
      `line-height: ${s.lineHeight}px;`,
      `letter-spacing: ${s.letterSpacingPercent ? s.letterSpacingPercent / 100 + "em" : "0"};`,
    ];
    if (s.textCase === "UPPER") rules.push("text-transform: uppercase;");
    const v = `--text-${slug(s.name)}`;
    textVars.push(`  ${v}-weight: ${weight};`, `  ${v}-size: ${s.size}px;`, `  ${v}-line: ${s.lineHeight}px;`, `  ${v}-tracking: ${s.letterSpacingPercent ? s.letterSpacingPercent / 100 + "em" : "0"};`);
    text.push(`.t-${slug(s.name)} { ${rules.join(" ")} }`);
  }
  return [
    `/* Generated by web/tools/build-tokens.mjs from docs/design/tokens.json (Figma \`${tokens.source.file}\`, read on ${tokens.source.readAt}). Do not edit. */`,
    "",
    ":root {",
    ...light,
    ...fixed,
    ...paints,
    ...effects,
    fontVar,
    ...textVars,
    "}",
    "",
    ':root[data-theme="dark"] {',
    ...dark,
    "}",
    "",
    ...text,
    "",
  ].join("\n");
}

function fail(what) {
  throw new Error(`unknown ${what}`);
}

const tokens = JSON.parse(fs.readFileSync(SOURCE, "utf8"));
const next = render(tokens);
if (process.argv.includes("--check")) {
  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== next) {
    console.error("web/public/css/tokens.css is stale. Run npm --prefix web run tokens.");
    process.exitCode = 1;
  } else {
    console.log("tokens.css matches docs/design/tokens.json.");
  }
} else {
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, next);
  console.log(`web/public/css/tokens.css written (${tokens.textStyles.length} text styles).`);
}
