#!/usr/bin/env node
// Renders the "Aero" section of docs/tokens.md from docs/design/tokens.json, the mirror of the Figma `Design`
// variables and text styles (ADR-031 § 8). The agent writes tokens.json from an MCP read; this script only renders.
// Everything between AERO_BEGIN and AERO_END is replaced; the rest of docs/tokens.md is kept byte for byte.
//
// Usage: node tools/gen-tokens.mjs           writes docs/tokens.md
//        node tools/gen-tokens.mjs --check   exits 1 when docs/tokens.md differs from tokens.json (no write)
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(root, "docs", "design", "tokens.json");
const TARGET = path.join(root, "docs", "tokens.md");
export const AERO_BEGIN = "<!-- aero:begin (generated by tools/gen-tokens.mjs from docs/design/tokens.json; do not edit) -->";
export const AERO_END = "<!-- aero:end -->";

const cell = (v) => String(v).replace(/\|/g, "\\|");

function valueCell(variable, mode) {
  const v = variable.values[mode];
  if (v && typeof v === "object" && v.alias) return "→ `" + v.alias + "`";
  return "`" + v + "`";
}

export function renderAero(tokens) {
  const out = [
    "## Aero",
    "",
    "Generated from the Figma file `" + tokens.source.file + "` (`" + tokens.source.fileKey + "`), read on " + tokens.source.readAt +
      ". Never edit this section by hand: change Figma, refresh [`design/tokens.json`](design/tokens.json) and run `node tools/gen-tokens.mjs`.",
    "",
  ];
  for (const c of tokens.collections) {
    out.push("### " + c.name + " (modes: " + c.modes.join(", ") + ")", "");
    out.push("| Token | " + c.modes.join(" | ") + " | Android | Usage |");
    out.push("|---|" + c.modes.map(() => "---|").join("") + "---|---|");
    for (const v of c.variables) {
      const modes = c.modes.map((m) => valueCell(v, m)).join(" | ");
      out.push("| `" + v.name + "` | " + modes + " | `" + (v.codeSyntax?.ANDROID ?? "") + "` | " + cell(v.description ?? "") + " |");
    }
    out.push("");
  }
  out.push("### Text styles", "");
  out.push("| Style | Family | Weight | Size | Line height | Letter spacing |");
  out.push("|---|---|---|---|---|---|");
  for (const s of tokens.textStyles) {
    out.push("| `" + s.name + "` | " + s.family + " | " + s.style + " | " + s.size + " | " + s.lineHeight + " | " + s.letterSpacingPercent + "% |");
  }
  return out.join("\n").trimEnd();
}

export function render(current, tokens) {
  const begin = current.indexOf(AERO_BEGIN);
  const end = current.indexOf(AERO_END);
  if (begin < 0 || end < begin) throw new Error("docs/tokens.md has no aero:begin / aero:end markers");
  return current.slice(0, begin + AERO_BEGIN.length) + "\n\n" + renderAero(tokens) + "\n\n" + current.slice(end);
}

function main() {
  const tokens = JSON.parse(fs.readFileSync(SOURCE, "utf8"));
  const current = fs.readFileSync(TARGET, "utf8");
  const next = render(current, tokens);
  if (process.argv.includes("--check")) {
    if (next !== current) {
      console.error("docs/tokens.md is out of date with docs/design/tokens.json. Run node tools/gen-tokens.mjs.");
      process.exitCode = 1;
    } else console.log("docs/tokens.md matches docs/design/tokens.json.");
    return;
  }
  fs.writeFileSync(TARGET, next);
  const count = tokens.collections.reduce((n, c) => n + c.variables.length, 0);
  console.log("docs/tokens.md: Aero section rendered (" + count + " variables, " + tokens.textStyles.length + " text styles).");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); }
  catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
